name: Feature Request
description: Suggest an idea for this project
title: "[REQ] "
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Before proceeding, please make sure:**
        > - Your request is not a duplicate
        > - The feature you are requesting has not already been implemented.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Select all that apply.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: os-other
    attributes:
      label: If you selected "Other", please specify
      placeholder: "e.g. FreeBSD, ChromeOS..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
